<?php

/**
 * Implementation of hook_install().
 */
function context_reaction_no_cache_install() {
  // Set weight to 99 so we're one of the last modules to run.
  db_query("UPDATE {system} SET weight = 99 WHERE name = 'context_reaction_no_cache'");
}

function context_reaction_no_cache_uninstall() {
  //Clear the page cache for the whole site, just in case out cache control has been too aggressive.
  cache_clear_all(NULL, 'cache_page', '*');
}